/**
 * 0.9.6 composer 回填（「回滚了但消息框是空的」）。
 *
 * 专家组定案的三条根因：
 *   R2 5 个回滚入口里只有 2 个回填 → 统一 refillComposer 出口
 *   R4 afterWrite 把**裸 uuid** 传给 openSession → `unknown session` 必抛且被
 *      `catch {}` 静默吞掉 → 视图重建从没生效过
 *   R1 目标会选到宿主注入的伪 user 行（通知），回填文本不是用户写的那句
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const src = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'client.js'), 'utf8')

/** 与 refillComposer 同构的边界选择 */
const pickForRefill = (rows, boundarySeq) => {
  const hit = rows.filter((r) => r && typeof r.seq === 'number' && r.seq <= boundarySeq && r.fullText)
  return hit.length ? hit[hit.length - 1] : null
}

/** 与 client.js 的 injected 同构（从源码里截出正则字面量校验覆盖面） */
const injectedSource = (() => {
  const m = src.match(/const injected = \(raw\) => (\/[\s\S]*?\/[gimsuy]*)\.test/)
  return m ? new RegExp(m[1].slice(1, m[1].lastIndexOf('/')), m[1].slice(m[1].lastIndexOf('/') + 1)) : null
})()

test('/undo：boundary 就是被回滚那条 → 回填它自己', () => {
  const rows = [
    { seq: 8,  fullText: '第一句' },
    { seq: 54, fullText: '要撤销的这句' },
    { seq: 89, fullText: '重放副本' },
  ]
  assert.equal(pickForRefill(rows, 54).fullText, '要撤销的这句')
})

test('AI 时钟按钮：boundary 是 AI 消息 → 取它之前那条用户消息', () => {
  const rows = [
    { seq: 8,  fullText: '我问的问题' },
    { seq: 18, fullText: null },              // assistant 没有 fullText
    { seq: 54, fullText: '下一句' },
  ]
  // boundary = 18（AI 消息 seq）
  assert.equal(pickForRefill(rows, 18).seq, 8, '取边界之前最后一条带全文的')
  // 边界之后的不该被取到
  assert.equal(pickForRefill(rows, 54).seq, 54)
})

test('无可用行 → 返回 null（调用方不回填，不写空串）', () => {
  assert.equal(pickForRefill([], 100), null)
  assert.equal(pickForRefill([{ seq: 5, fullText: null }], 100), null)
  assert.equal(pickForRefill([{ seq: 500, fullText: 'x' }], 100), null, '只在边界之后的不能被取到')
})

test('R4：afterWrite 必须传带 session- 前缀的 id 给 openSession', () => {
  const m = src.match(/var afterWrite = \([\s\S]*?\n    \}/)
  assert.ok(m, '找不到 afterWrite')
  assert.ok(/openSession\(rawSid\)/.test(m[0]),
    'openSession 收到裸 uuid 会抛 `sessions.retain: unknown session`，外层 catch {} 静默 → 视图重建从未生效')
  assert.ok(!/openSession\(bare\)|openSession\(bareSessionId/.test(m[0]),
    '不得传裸 id')
})

test('R2：所有 revert 入口都接了 refillComposer', () => {
  const calls = (src.match(/\brefillComposer\(/g) || []).length
  // 三个回滚入口：runUndo(/undo) + runRevert(AI 时钟) + runUserRevert(悬停)
  // 注意：定义写法是 `refillComposer = (`，不匹配 `refillComposer(`
  assert.equal(calls, 3, `refillComposer 调用 ${calls} 处，应为 3 个回滚入口`)
  assert.ok(/var refillComposer = \(/.test(src), '缺 refillComposer 定义')
  // 反例：restore / redo 不该回填（它们是加回内容，不是删）
  const redo = src.match(/var runRedo = \(\) => \{[\s\S]*?\n    \}/)
  assert.ok(redo && !/refillComposer\(/.test(redo[0]), '/redo 不应回填 composer')
})

test('R1：injected 必须挡住宿主注入的伪 user 通知行', () => {
  assert.ok(injectedSource, '源码里找不到 injected 正则')
  const shouldBlock = [
    '<system-reminder>系统提示</system-reminder>',
    'current runtime context 如下',
    // 全部取自 120 份日志的真实样本
    'background job bash-358 (bash: END=$((SECONDS+2700)); i=0\nwhile ...',
    'Agent b813ff57-de81-426b-8519-3a6e3b83f9ef sent a message: 完成了',
    'Background subagent b813ff57-de81-426b-8519-3a6e3b83f9ef finished and will do no further work',
    '[model changed: assistant turns above this point were generated by a different model]',
  ]
  const shouldAllow = [
    '查询一下所有智能体的进度吧',
    '分配几个子代理把模型广场的模型价格什么的做好',
    'agent 是什么意思',
    'Background job 是我自己的问题',
    'background job 是我自己的问题',
    'Agent 变成名词的用法呢',
    '后台任务 background 作业怎么理解',
  ]
  for (const s of shouldBlock) assert.ok(injectedSource.test(s), `应被排除: ${s.slice(0, 40)}`)
  for (const s of shouldAllow) assert.ok(!injectedSource.test(s), `不应被误杀: ${s.slice(0, 40)}`)
})

test('R2：不再用静默 catch 吞掉 setDraft 失败', () => {
  const m = src.match(/var refillComposer = [\s\S]*?\n    \}/)
  assert.ok(m, '找不到 refillComposer')
  assert.ok(/console\.warn/.test(m[0]), 'setDraft 失败必须留痕，原先 catch {} 完全静默')
  assert.ok(!/catch \{ \/\* 回填失败不阻断 \*\/ \}/.test(m[0]))
})
